[2020-12-03T18:18:03-0800] [MainThread] [C] [toil.jobStores.abstractJobStore] Repairing job: kind-parse_config_file/instance-yzt_3sn0
[2020-12-03T18:18:03-0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mustard.
[2020-12-03T18:18:03-0800] [MainThread] [I] [toil.leader] Issued job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
[2020-12-03T18:18:04-0800] [MainThread] [I] [toil.worker] Redirecting logging to /scratch/drkthomp/workDir/node-f6686f9d-cbd0-41d1-8aff-fcfb902a721a-e8611b53-bdab-4598-acae-87977f99831e/tmp_d3zq3z6/worker_log.txt
[2020-12-03T18:18:05-0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker parse_config_file file:/scratch/drkthomp/jobStore kind-parse_config_file/instance-yzt_3sn0.
[2020-12-03T18:18:05-0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
[2020-12-03T18:18:05-0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
[2020-12-03T18:18:05-0800] [MainThread] [W] [toil.leader] Log from job kind-parse_config_file/instance-yzt_3sn0 follows:
=========>
	[2020-12-03T18:18:04-0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-12-03T18:18:04-0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mustard.
	[2020-12-03T18:18:04-0800] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:333: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:338: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:350: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    max_cores)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 362, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    'does not contain a hla_haplotype_files entry.\nCannot haplotype '
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-12-03T18:18:04-0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mustard
<=========
[2020-12-03T18:18:05-0800] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 with ID kind-parse_config_file/instance-yzt_3sn0 to 1
[2020-12-03T18:18:05-0800] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2020-12-03T18:18:05-0800] [MainThread] [I] [toil.leader] Issued job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 2.0 G
[2020-12-03T18:18:05-0800] [MainThread] [I] [toil.worker] Redirecting logging to /scratch/drkthomp/workDir/node-f6686f9d-cbd0-41d1-8aff-fcfb902a721a-e8611b53-bdab-4598-acae-87977f99831e/tmp607xjn_g/worker_log.txt
[2020-12-03T18:18:06-0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker parse_config_file file:/scratch/drkthomp/jobStore kind-parse_config_file/instance-yzt_3sn0.
[2020-12-03T18:18:06-0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
[2020-12-03T18:18:06-0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
[2020-12-03T18:18:06-0800] [MainThread] [W] [toil.leader] Log from job kind-parse_config_file/instance-yzt_3sn0 follows:
=========>
	[2020-12-03T18:18:05-0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-12-03T18:18:05-0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mustard.
	[2020-12-03T18:18:06-0800] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:333: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:338: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:350: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    max_cores)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 362, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    'does not contain a hla_haplotype_files entry.\nCannot haplotype '
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-12-03T18:18:06-0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mustard
<=========
[2020-12-03T18:18:06-0800] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 with ID kind-parse_config_file/instance-yzt_3sn0 to 0
[2020-12-03T18:18:06-0800] [MainThread] [W] [toil.leader] Job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 with ID kind-parse_config_file/instance-yzt_3sn0 is completely failed
[2020-12-03T18:18:09-0800] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2020-12-03T18:18:09-0800] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
Traceback (most recent call last):
  File "/private/home/drkthomp/protect/venv/bin/ProTECT", line 11, in <module>
    load_entry_point('protect', 'console_scripts', 'ProTECT')()
  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 1028, in main
    Job.Runner.startToil(start, params)
  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 798, in startToil
    return toil.restart()
  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/common.py", line 878, in restart
    return self._runMainLoop(rootJobGraph)
  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/common.py", line 1138, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/leader.py", line 269, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/scratch/drkthomp/jobStore' contains 1 failed jobs: 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0
Log from job 'parse_config_file' kind-parse_config_file/instance-yzt_3sn0 follows:
=========>
	[2020-12-03T18:18:05-0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-12-03T18:18:05-0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mustard.
	[2020-12-03T18:18:06-0800] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:333: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:338: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py:350: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/private/home/drkthomp/protect/venv/lib/python3.6/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    max_cores)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 362, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/private/home/drkthomp/protect/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    'does not contain a hla_haplotype_files entry.\nCannot haplotype '
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-12-03T18:18:06-0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mustard
<=========
